[package]
name = "js-from-rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi9", "async"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2.1.3"
